import type { Coupon, Product } from "./types";

/**
 * Catálogo de demonstração usado enquanto o Firebase não está configurado.
 * As imagens estão propositalmente vazias — basta preencher `images` com as
 * URLs das suas fotos (ou cadastrar os produtos no Firestore).
 */
export const SAMPLE_PRODUCTS: Product[] = [
  {
    id: "blusa-seda-lua",
    name: "Blusa de Seda Lua",
    slug: "blusa-de-seda-lua",
    category: "blusas",
    description:
      "Blusa em seda com caimento fluido e acabamento artesanal. Peça versátil para o dia e para a noite.",
    price: 289.9,
    salePrice: 239.9,
    images: [],
    sizes: ["PP", "P", "M", "G"],
    colors: ["Off White", "Dourado", "Preto"],
    variants: [],
    stock: 12,
    featured: true,
    bestSeller: true,
    createdAt: "2026-09-10T12:00:00.000Z",
  },
  {
    id: "blusa-cropped-aura",
    name: "Blusa Cropped Aura",
    slug: "blusa-cropped-aura",
    category: "blusas",
    description: "Cropped de manga longa em malha canelada, modelagem ajustada ao corpo.",
    price: 179.9,
    salePrice: null,
    images: [],
    sizes: ["P", "M", "G"],
    colors: ["Off White", "Cinza"],
    variants: [],
    stock: 3,
    featured: true,
    createdAt: "2026-09-02T12:00:00.000Z",
  },
  {
    id: "calca-alfaiataria-noite",
    name: "Calça Alfaiataria Noite",
    slug: "calca-alfaiataria-noite",
    category: "calcas",
    description: "Alfaiataria de cintura alta com pregas frontais e corte reto alongado.",
    price: 349.9,
    salePrice: 299.9,
    images: [],
    sizes: ["36", "38", "40", "42"],
    colors: ["Preto", "Cinza"],
    variants: [],
    stock: 8,
    bestSeller: true,
    createdAt: "2026-08-28T12:00:00.000Z",
  },
  {
    id: "calca-wide-areia",
    name: "Calça Wide Areia",
    slug: "calca-wide-areia",
    category: "calcas",
    description: "Modelagem wide leg em tecido leve, perfeita para climas quentes.",
    price: 279.9,
    salePrice: null,
    images: [],
    sizes: ["36", "38", "40"],
    colors: ["Off White", "Dourado"],
    variants: [],
    stock: 2,
    featured: true,
    createdAt: "2026-09-18T12:00:00.000Z",
  },
  {
    id: "corset-dourado",
    name: "Corset Dourado Selene",
    slug: "corset-dourado-selene",
    category: "corset",
    description: "Corset estruturado com detalhe em cetim dourado e fechamento por ilhoses.",
    price: 429.9,
    salePrice: 379.9,
    images: [],
    sizes: ["P", "M", "G"],
    colors: ["Dourado", "Preto"],
    variants: [],
    stock: 4,
    featured: true,
    bestSeller: true,
    createdAt: "2026-09-20T12:00:00.000Z",
  },
  {
    id: "corset-classic",
    name: "Corset Clássico Perla",
    slug: "corset-classico-perla",
    category: "corset",
    description: "Corset clássico em tecido acetinado com barbatanas internas.",
    price: 389.9,
    salePrice: null,
    images: [],
    sizes: ["PP", "P", "M"],
    colors: ["Off White", "Cinza"],
    variants: [],
    stock: 15,
    createdAt: "2026-07-14T12:00:00.000Z",
  },
];

/** Cupons de demonstração — no Firebase, use a coleção `coupons`. */
export const SAMPLE_COUPONS: Coupon[] = [
  { code: "DLUA10", type: "percent", value: 10 },
  { code: "BEMVINDA50", type: "fixed", value: 50, minSubtotal: 300 },
];
