/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BuscaRouteImport } from './routes/busca'
import { Route as CarrinhoRouteImport } from './routes/carrinho'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as ContaRouteImport } from './routes/conta'
import { Route as PrivacidadeRouteImport } from './routes/privacidade'
import { Route as RastreamentoRouteImport } from './routes/rastreamento'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as TermosRouteImport } from './routes/termos'
import { Route as CategoriaSlugRouteImport } from './routes/categoria.$slug'
import { Route as ContaPedidosRouteImport } from './routes/conta_.pedidos'
import { Route as PedidoConfirmacaoRouteImport } from './routes/pedido.confirmacao'
import { Route as ProdutoIdRouteImport } from './routes/produto.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BuscaRoute = BuscaRouteImport.update({
  id: '/busca',
  path: '/busca',
  getParentRoute: () => rootRouteImport,
} as any)
const CarrinhoRoute = CarrinhoRouteImport.update({
  id: '/carrinho',
  path: '/carrinho',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ContaRoute = ContaRouteImport.update({
  id: '/conta',
  path: '/conta',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadeRoute = PrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const RastreamentoRoute = RastreamentoRouteImport.update({
  id: '/rastreamento',
  path: '/rastreamento',
  getParentRoute: () => rootRouteImport,
} as any)
const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const TermosRoute = TermosRouteImport.update({
  id: '/termos',
  path: '/termos',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriaSlugRoute = CategoriaSlugRouteImport.update({
  id: '/categoria/$slug',
  path: '/categoria/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ContaPedidosRoute = ContaPedidosRouteImport.update({
  id: '/conta_/pedidos',
  path: '/conta/pedidos',
  getParentRoute: () => rootRouteImport,
} as any)
const PedidoConfirmacaoRoute = PedidoConfirmacaoRouteImport.update({
  id: '/pedido/confirmacao',
  path: '/pedido/confirmacao',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdutoIdRoute = ProdutoIdRouteImport.update({
  id: '/produto/$id',
  path: '/produto/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/busca': typeof BuscaRoute
  '/carrinho': typeof CarrinhoRoute
  '/checkout': typeof CheckoutRoute
  '/conta': typeof ContaRoute
  '/privacidade': typeof PrivacidadeRoute
  '/rastreamento': typeof RastreamentoRoute
  '/sobre': typeof SobreRoute
  '/termos': typeof TermosRoute
  '/categoria/$slug': typeof CategoriaSlugRoute
  '/conta/pedidos': typeof ContaPedidosRoute
  '/pedido/confirmacao': typeof PedidoConfirmacaoRoute
  '/produto/$id': typeof ProdutoIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/busca': typeof BuscaRoute
  '/carrinho': typeof CarrinhoRoute
  '/checkout': typeof CheckoutRoute
  '/conta': typeof ContaRoute
  '/privacidade': typeof PrivacidadeRoute
  '/rastreamento': typeof RastreamentoRoute
  '/sobre': typeof SobreRoute
  '/termos': typeof TermosRoute
  '/categoria/$slug': typeof CategoriaSlugRoute
  '/conta/pedidos': typeof ContaPedidosRoute
  '/pedido/confirmacao': typeof PedidoConfirmacaoRoute
  '/produto/$id': typeof ProdutoIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/busca': typeof BuscaRoute
  '/carrinho': typeof CarrinhoRoute
  '/checkout': typeof CheckoutRoute
  '/conta': typeof ContaRoute
  '/privacidade': typeof PrivacidadeRoute
  '/rastreamento': typeof RastreamentoRoute
  '/sobre': typeof SobreRoute
  '/termos': typeof TermosRoute
  '/categoria/$slug': typeof CategoriaSlugRoute
  '/conta_/pedidos': typeof ContaPedidosRoute
  '/pedido/confirmacao': typeof PedidoConfirmacaoRoute
  '/produto/$id': typeof ProdutoIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/busca'
    | '/carrinho'
    | '/checkout'
    | '/conta'
    | '/privacidade'
    | '/rastreamento'
    | '/sobre'
    | '/termos'
    | '/categoria/$slug'
    | '/conta/pedidos'
    | '/pedido/confirmacao'
    | '/produto/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/busca'
    | '/carrinho'
    | '/checkout'
    | '/conta'
    | '/privacidade'
    | '/rastreamento'
    | '/sobre'
    | '/termos'
    | '/categoria/$slug'
    | '/conta/pedidos'
    | '/pedido/confirmacao'
    | '/produto/$id'
  id:
    | '__root__'
    | '/'
    | '/busca'
    | '/carrinho'
    | '/checkout'
    | '/conta'
    | '/privacidade'
    | '/rastreamento'
    | '/sobre'
    | '/termos'
    | '/categoria/$slug'
    | '/conta_/pedidos'
    | '/pedido/confirmacao'
    | '/produto/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BuscaRoute: typeof BuscaRoute
  CarrinhoRoute: typeof CarrinhoRoute
  CheckoutRoute: typeof CheckoutRoute
  ContaRoute: typeof ContaRoute
  PrivacidadeRoute: typeof PrivacidadeRoute
  RastreamentoRoute: typeof RastreamentoRoute
  SobreRoute: typeof SobreRoute
  TermosRoute: typeof TermosRoute
  CategoriaSlugRoute: typeof CategoriaSlugRoute
  ContaPedidosRoute: typeof ContaPedidosRoute
  PedidoConfirmacaoRoute: typeof PedidoConfirmacaoRoute
  ProdutoIdRoute: typeof ProdutoIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/busca': {
      id: '/busca'
      path: '/busca'
      fullPath: '/busca'
      preLoaderRoute: typeof BuscaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/carrinho': {
      id: '/carrinho'
      path: '/carrinho'
      fullPath: '/carrinho'
      preLoaderRoute: typeof CarrinhoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conta': {
      id: '/conta'
      path: '/conta'
      fullPath: '/conta'
      preLoaderRoute: typeof ContaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidade': {
      id: '/privacidade'
      path: '/privacidade'
      fullPath: '/privacidade'
      preLoaderRoute: typeof PrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rastreamento': {
      id: '/rastreamento'
      path: '/rastreamento'
      fullPath: '/rastreamento'
      preLoaderRoute: typeof RastreamentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/termos': {
      id: '/termos'
      path: '/termos'
      fullPath: '/termos'
      preLoaderRoute: typeof TermosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categoria/$slug': {
      id: '/categoria/$slug'
      path: '/categoria/$slug'
      fullPath: '/categoria/$slug'
      preLoaderRoute: typeof CategoriaSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conta_/pedidos': {
      id: '/conta_/pedidos'
      path: '/conta/pedidos'
      fullPath: '/conta/pedidos'
      preLoaderRoute: typeof ContaPedidosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pedido/confirmacao': {
      id: '/pedido/confirmacao'
      path: '/pedido/confirmacao'
      fullPath: '/pedido/confirmacao'
      preLoaderRoute: typeof PedidoConfirmacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produto/$id': {
      id: '/produto/$id'
      path: '/produto/$id'
      fullPath: '/produto/$id'
      preLoaderRoute: typeof ProdutoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BuscaRoute: BuscaRoute,
  CarrinhoRoute: CarrinhoRoute,
  CheckoutRoute: CheckoutRoute,
  ContaRoute: ContaRoute,
  PrivacidadeRoute: PrivacidadeRoute,
  RastreamentoRoute: RastreamentoRoute,
  SobreRoute: SobreRoute,
  TermosRoute: TermosRoute,
  CategoriaSlugRoute: CategoriaSlugRoute,
  ContaPedidosRoute: ContaPedidosRoute,
  PedidoConfirmacaoRoute: PedidoConfirmacaoRoute,
  ProdutoIdRoute: ProdutoIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
